version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/kundusurinder/Hrm"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "php"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "javascript"